In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/Amazon Sale Report.csv', sep=',', low_memory=False)
display(df.head())
display(df.info())
display(df.describe())
display(df.isna().sum())
display(df.sample(10))

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

None

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
120760,120760,405-2244385-2720353,06-06-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3800,JNE3800-KR-L,Western Dress,...,INR,735.0,PALAKKAD,KERALA,678006.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
31457,31457,171-8588805-2190744,04-11-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,JNE3334,JNE3334-KR-XXL,kurta,...,INR,318.0,NEW DELHI,DELHI,110085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
88522,88522,404-9271246-5475502,05-02-22,Shipped,Amazon,Amazon.in,Expedited,SET308,SET308-KR-PP-S,Set,...,INR,696.0,NANDIVARAM GUDUVANCHERI,TAMIL NADU,603202.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
63592,63592,404-7653319-7921902,05-20-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-XL,Set,...,INR,648.0,HYDERABAD,TELANGANA,500075.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
118234,118234,171-1659581-9791527,06-08-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3800,JNE3800-KR-XS,Western Dress,...,INR,735.0,KALAMASSERY,KERALA,682021.0,IN,NaN,False,NaN,False
10991,10991,402-5793741-8523554,04-23-22,Shipped - Returned to Seller,Merchant,Amazon.in,Standard,SET345,SET345-KR-NP-M,Set,...,INR,626.0,Dhanbad,JHARKHAND,828204.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
15542,15542,404-1471084-9713953,04-21-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,SET300,SET300-KR-NP-L,Set,...,INR,999.0,KULGAM,JAMMU & KASHMIR,192231.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
83999,83999,407-7717792-8653901,05-04-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3739,JNE3739-KR-XXXL,kurta,...,INR,459.0,ATELI,HARYANA,123021.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,False
74930,74930,171-0813742-0813135,05-10-22,Shipped,Amazon,Amazon.in,Expedited,SET236,SET236-KR-PP-L,Set,...,INR,788.0,UDUPI,KARNATAKA,576101.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
97307,97307,404-4329170-1924342,06-24-22,Shipped,Amazon,Amazon.in,Expedited,SET431,SET431-KR-NP-L,Set,...,INR,899.0,NILAMBUR,KERALA,679329.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [8]:
data = pd.read_csv('../data/raw/Sale Report.csv', sep=',', low_memory=False)
df = pd.DataFrame(data)
display(df.head())
display(df.info())
display(df.describe())
display(df.isna().sum())
display(df.sample(10))

   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9271 entries, 0 to 9270
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   index       9271 non-null   int64
 1   SKU Code    9188 non-null   object
 2   Design No.  9235 non-null   object
 3   Stock       9235 non-null   float64
 4   Category    9226 non-null   object
 5   Size        9235 non-null   object
 6   Color       9226 non-null   object
dtypes: float64(1), int64(1), object(5)
memory usage: 507.1+ KB

None

             index        Stock
count  9271.000000  9235.000000
mean   4635.000000    26.246454
std    2676.451507    58.462891
min       0.000000     0.000000
25%    2317.500000     3.000000
50%    4635.000000     8.000000
75%    6952.500000    31.000000
max    9270.000000  1234.000000

index          0
SKU Code      83
Design No.    36
Stock         36
Category      45
Size          36
Color         45
dtype: int64

      index           SKU Code Design No.  Stock    Category  Size       Color
405     405     BTM038-PP-XXXL     BTM038    1.0     PALAZZO  XXXL       Black
6305   6305      JNE3837-KR-XS    JNE3837   55.0       KURTA    XS       Black
5237   5237       JNE3656-TP-L    JNE3656   70.0         TOP     L       Black
5752   5752      JNE3745-KR-XL    JNE3745   99.0       KURTA    XL  Teal Green
3707   3707      JNE3337-KR-XL    JNE3337    2.0       KURTA    XL       Peach
7058   7058      NW023-ST-SR-L      NW023   32.0  NIGHT WEAR     L        Blue
8849   8849  SET361-KR-NP-XXXL     SET361    0.0         SET  XXXL       White
7689   7689    SET152-KR-NP-XS     SET152    3.0         SET    XS      Orange
1062   1062         J0090-TP-M      J0090    1.0         TOP     M         Red
7626   7626     SET131-KR-NP-S     SET131   10.0   KURTA SET     S        Blue